#!/bin/ksh
set -e 
failed=0

workdir="$PWD"
tmpdir=$(TMPDIR="$workdir" mktemp -d)

port=13245
www="$tmpdir/www"
mkdir "$www"
shellweb_cmd="${workdir}/shellweb -d $www -p $port"

test_name=${0##*/test-}

run_shellweb(){
	$shellweb_cmd &
	sleep 1
	
}

kill_shellweb() {
	pkill -u $(id -u) -f "$shellweb_cmd"
	pkill -u $(id -u) -x nc
}

cleanup() {
	rm -rf $tmpdir
}

fail() {
	for msg in "$@"; do
		failed=1
		echo "FAIL in $test_name $msg"
	done
	return 1
}

finish() {
	kill_shellweb || true
	cleanup || true
	test $failed -gt 0 || echo "$test_name ==> OK" 
}

trap 'finish' EXIT

echo "test: $test_name"
