#!/bin/ksh 
#check for 404 response

. ${0%/*}/common

run_shellweb

link="${www}/XXXXXX"
test ! $# -gt 0 || link=$1
check="HTTP/1.0 404 Not found"
response=$(printf "GET $link HTTP/1.0\r\n\r\n" | \
	 nc -w 1 127.0.0.1 $port | head -n 1 | tr -d '\r')
test x"$response" = x"$check" || fail "$response"
