#!/bin/ksh
#check for 403 response

. ${0%/*}/common

link="/"
test ! $# -gt 0 || link=$1

run_shellweb
check="HTTP/1.0 403 Not allowed" 
response=$(printf "GET $link HTTP/1.0\r\n\r\n" | \
	 nc -w 1 127.0.0.1 $port | head -n 1 | tr -d '\r')
test x"$response" = x"$check" || fail "$response"
