#!/bin/ksh
#check for 200 response

. ${0%/*}/common

path="/test.txt"
touch "${www}${path}"

run_shellweb

check="HTTP/1.1 200 OK"
response=$(printf "GET $path HTTP/1.0\r\n\r\n" | \
	 nc -w 1 127.0.0.1 $port | head -n 1 | tr -d '\r')
test x"$response" = x"$check" || fail "$response"
