#!/bin/ksh
#check for 416 response

. ${0%/*}/common

link="./tests/home.html"
bytes_request="25-14"
while getopts "l:r:" OPT; do case $OPT in
	f)	file=$OPTARG;;
	r)	byte_request=$OPTARG;;
esac; done
shift $((OPTIND - 1))
run_shellweb
request_file=$(mktemp -p $www)
cp "$link" "$request_file"
response=$(
	{ printf "GET ${request_file#$www} HTTP/1.1\r\n"
 	  printf "Range: bytes="$bytes_request"\r\n\r\n"
	} | nc -w 1 127.0.0.1 $port | head -n 1 | tr -d '\r'
)
check="HTTP/1.1 416 Range Not Satisfiable"
test x"$response" = x"$check" || fail "$response"
