#!/bin/ksh
#check for equality

. ${0%/*}/common

path="/test.txt"
source="${www}/${path}"
response="${tmpdir}/response"
difference="${tmpdir}/diff"

cat >$source <<EOF
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum.
EOF

run_shellweb 

printf "GET $path HTTP/1.0\r\n\r\n" | \
	$nc -w 5 127.0.0.1 $port | tr -d '\r' >$response

firstline=$(head -n 1 "$response")
check="HTTP/1.1 200 OK"
test x"$firstline" = x"$check" || fail "expected: '$check'; got: '$firstline'"
sed -i '1,/^$/ d' "$response"
diff -u "$source" "$response" >$difference || { fail "response didn't match source file"; cat "$difference"; }
