#!/bin/ksh
#check for 403 response

. ${0%/*}/common

path="/foo.txt"
touch "${www}${path}"
chmod 000 "${www}${path}"

run_shellweb

check="HTTP/1.0 403 Not allowed" 
response=$(printf "GET $path HTTP/1.0\r\n\r\n" | \
	 nc -w 1 127.0.0.1 $port | head -n 1 | tr -d '\r')
test x"$response" = x"$check" || fail "$response"
