#!/bin/ksh
#check for equality

. ${0%/*}/common

file="./tests/home.html"
test ! $# -gt 0 || file="$1"
test -f "$file" || fail "$file is incorrect"
run_shellweb 
request=$(TMPDIR="$www" mktemp request.XXXXXXXX)
cp "$file" "$request"
response=$(TMPDIR="$tmpdir" mktemp response.XXXXXXXX)
send="${request#$www}"
printf "GET $send HTTP/1.0\r\n\r\n" | \
	nc -w 1 127.0.0.1 $port | tr -d '\r'  >> "$response" 
header=$(head -n 1 $response)
check="HTTP/1.1 200 OK"
test x"$header" = x"$check" || fail "$header"
sed -i '1,/^$/ d' "$response"
cmp -s "$request" "$response" || fail "files don't match"
